"""Markdown report generation."""

from __future__ import annotations

from pathlib import Path

from mmsafe.metrics.aggregator import generate_summary
from mmsafe.pipeline.result_types import EvalRun


def generate_markdown_report(run: EvalRun, output_path: Path) -> Path:
    """Generate a Markdown report from an evaluation run."""
    summary = generate_summary(run)
    overall = summary["overall"]

    lines: list[str] = []
    _h = lines.append

    _h(f"# MMSAFE-Bench Safety Report: {summary['config_name']}")
    _h("")
    _h(f"**Run ID**: `{summary['run_id']}`  ")
    _h(f"**Duration**: {summary.get('duration_seconds', 0):.1f}s  ")
    _h(f"**Total Samples**: {overall['total_samples']}  ")
    _h("")

    # Overall metrics
    _h("## Overall Metrics")
    _h("")
    _h("| Metric | Value |")
    _h("|--------|-------|")
    _h(f"| Attack Success Rate (ASR) | {overall['attack_success_rate']:.2%} |")
    _h(f"| 95% CI | [{overall['asr_ci'][0]:.2%}, {overall['asr_ci'][1]:.2%}] |")
    _h(f"| Refusal Rate | {overall['refusal_rate']:.2%} |")
    _h(f"| False Refusal Rate | {overall['false_refusal_rate']:.2%} |")
    _h(f"| Errored Samples | {overall['samples_errored']} |")
    _h("")

    # By model
    if summary["by_model"]:
        _h("## Results by Model")
        _h("")
        _h("| Model | ASR | Refusal Rate | Samples |")
        _h("|-------|-----|-------------|---------|")
        for model, data in sorted(summary["by_model"].items()):
            _h(f"| {model} | {data['asr']:.2%} | {data['rr']:.2%} | {data['samples']} |")
        _h("")

    # By attack strategy
    if summary["by_attack"]:
        _h("## Results by Attack Strategy")
        _h("")
        _h("| Strategy | ASR | Samples |")
        _h("|----------|-----|---------|")
        for attack, data in sorted(summary["by_attack"].items(), key=lambda x: -x[1]["asr"]):
            _h(f"| {attack} | {data['asr']:.2%} | {data['samples']} |")
        _h("")

    # By hazard category
    if summary["by_category"]:
        _h("## Results by Hazard Category")
        _h("")
        _h("| Category | ASR | Refusal Rate | Samples |")
        _h("|----------|-----|-------------|---------|")
        for cat, data in sorted(summary["by_category"].items()):
            _h(f"| {cat} | {data['asr']:.2%} | {data['rr']:.2%} | {data['samples']} |")
        _h("")

    _h("---")
    _h("*Generated by [MMSAFE-Bench](https://github.com/ogulcanaydogan/MMSAFE-Bench)*")

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines) + "\n")
    return output_path
